spring:
    application:
        name: TaskManager
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://dpg-csfkgctsvqrc73fgfhm0-a.oregon-postgres.render.com/employe
        username: employe_user
        password: YOt4jgdrvKqXHzBl7hb2qKL2cHoxqEqh
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update

messages_en_US:
    properties:
        employee-not-found: Employee not found
        employee-already-exists: messageSource.getMessage("employee-already-exists", null, locale)
        employee-well-added: Employee is well added


    
messages_fr_FR:
    properties:
        employee-not-found: Employé ibtrouvable
        employee-already-exists: Employé existe déjà
        employee-well-added: Employé est bien ajouté

